-- ============================================================================
-- Saints Crew — 04. Orders
--
-- orders, order_items
--
-- ADDITIONS BEYOND §6's COLUMN LIST, flagged rather than added silently:
--   * contact_email / contact_phone — §5.4 requires email for the confirmation
--     and phone for delivery. A guest order has no `customers` row to read them
--     from, so the order must carry them.
--   * shipping_* columns — an order has to record where it went. §6's list has
--     no address reference, but a fulfilled order without a delivery address is
--     not fulfillable. These are a SNAPSHOT, deliberately not a foreign key to
--     `addresses`: if a customer later edits or deletes a saved address, the
--     historical order must still show where that parcel actually shipped.
--   * currency — pinned to INR so a future non-INR row can't be misread.
-- ============================================================================

create table public.orders (
  id                 uuid primary key default gen_random_uuid(),

  -- Human-facing order number. Customers quote this in emails and on WhatsApp;
  -- a raw uuid is unusable for that. Generated by the sequence below.
  order_number       text not null unique,

  customer_id        uuid references auth.users (id) on delete set null,

  status             text not null default 'pending_payment'
                       check (status in (
                         'pending_payment',  -- Razorpay order created, not yet paid
                         'paid',             -- signature verified server-side
                         'shipped',
                         'delivered',
                         'cancelled',
                         'refunded'
                       )),

  -- Contact details, required for every order including guests (§5.4).
  contact_email      text not null,
  contact_phone      text not null,

  -- Delivery address snapshot — see the header note on why this isn't an FK.
  shipping_name      text not null,
  shipping_line1     text not null,
  shipping_line2     text,
  shipping_city      text not null,
  shipping_state     text not null,
  shipping_pincode   text not null check (shipping_pincode ~ '^[1-9][0-9]{5}$'),
  shipping_country   text not null default 'IN',

  -- Whole rupees, matching products.price.
  subtotal           integer not null check (subtotal >= 0),
  shipping_fee       integer not null default 0 check (shipping_fee >= 0),
  total              integer not null check (total >= 0),
  currency           text not null default 'INR' check (currency = 'INR'),

  razorpay_order_id   text unique,
  razorpay_payment_id text unique,

  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  paid_at            timestamptz,

  -- Arithmetic guard. Cheap, and it catches a bad total before it reaches
  -- Razorpay rather than after a customer has been charged the wrong amount.
  constraint orders_total_matches_parts check (total = subtotal + shipping_fee),

  -- A paid order must have proof of payment. Enforcing it here means no code
  -- path can mark an order paid without the Razorpay payment id.
  constraint orders_paid_has_payment_id check (
    status not in ('paid', 'shipped', 'delivered')
    or (razorpay_payment_id is not null and paid_at is not null)
  )
);

comment on table public.orders is
  'Orders. Only an Edge Function using the service-role key may write here — payment must be verified server-side (§5.4).';
comment on column public.orders.customer_id is
  'on delete set null: a deleted account must not erase sales records.';

create index orders_customer_id_created_idx on public.orders (customer_id, created_at desc);
create index orders_status_idx on public.orders (status);

create trigger orders_set_updated_at
  before update on public.orders
  for each row execute function public.set_updated_at();


-- ----------------------------------------------------------------------------
-- Human-readable order numbers: SC-10001, SC-10002, …
-- ----------------------------------------------------------------------------
create sequence public.order_number_seq start with 10001;

create or replace function public.set_order_number()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.order_number is null or new.order_number = '' then
    new.order_number := 'SC-' || nextval('public.order_number_seq');
  end if;
  return new;
end;
$$;

create trigger orders_set_order_number
  before insert on public.orders
  for each row execute function public.set_order_number();


-- ----------------------------------------------------------------------------
-- order_items
--
-- `price_at_purchase` is the whole reason this table doesn't just join to
-- products: what the customer paid must never change when the catalog price
-- changes. `product_name` and `variant_*` are snapshotted for the same reason —
-- an order confirmation from six months ago has to still be readable after a
-- product is renamed or delisted.
-- ----------------------------------------------------------------------------
create table public.order_items (
  id                 uuid primary key default gen_random_uuid(),
  order_id           uuid not null references public.orders (id) on delete cascade,

  -- restrict, not cascade: deleting a variant must not silently rewrite history.
  product_variant_id uuid not null references public.product_variants (id) on delete restrict,

  -- Snapshot of what was actually bought, for display after catalog changes.
  product_name       text not null,
  variant_size       text not null,
  variant_color      text not null,

  qty                integer not null check (qty > 0),
  price_at_purchase  integer not null check (price_at_purchase >= 0),

  created_at         timestamptz not null default now()
);

comment on column public.order_items.price_at_purchase is
  'Whole rupees, frozen at purchase. Never recompute an old order from the live catalog price.';

create index order_items_order_id_idx on public.order_items (order_id);
